### ISSUE TITLE
Crash with Create Fabric build 1417

### ISSUE THREAD

**Issue by Spiderach** [ReMelon/create_crystallized#1]
The most recent update to Create Fabric crashes with this mod, but it looks like just a dependency listing issue. Changing the fabric.mod.json to list the new version seems to be a cursory solution, though I didn't test things out beyond loading in and seeing the items.

**Comment by ReMelon** [comment]
Here you go
https://github.com/ReMelon/create_crystallized_fabric/actions/runs/8764479901
